// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chirps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChip = `-- name: CreateChip :one
INSERT INTO chirps(id, user_id, body)
VALUES (
  $1,
  $2,
  $3
) RETURNING id, user_id, body, created_at, updated_at
`

type CreateChipParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Body   string
}

func (q *Queries) CreateChip(ctx context.Context, arg CreateChipParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, createChip, arg.ID, arg.UserID, arg.Body)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChirpById = `-- name: DeleteChirpById :exec
DELETE FROM chirps
WHERE id = $1
`

func (q *Queries) DeleteChirpById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChirpById, id)
	return err
}

const deleteChirps = `-- name: DeleteChirps :exec
DELETE FROM chirps
`

func (q *Queries) DeleteChirps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteChirps)
	return err
}

const getAllChirps = `-- name: GetAllChirps :many
SELECT id, user_id, body, created_at, updated_at FROM chirps
ORDER BY created_at
ASC
`

func (q *Queries) GetAllChirps(ctx context.Context) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, getAllChirps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChirpById = `-- name: GetChirpById :one
SELECT id, user_id, body, created_at, updated_at FROM chirps
WHERE id=$1
`

func (q *Queries) GetChirpById(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, getChirpById, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChirpByIdAndUserId = `-- name: GetChirpByIdAndUserId :one
SELECT id, user_id, body, created_at, updated_at FROM chirps
WHERE id = $1 and user_id = $2
`

type GetChirpByIdAndUserIdParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetChirpByIdAndUserId(ctx context.Context, arg GetChirpByIdAndUserIdParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, getChirpByIdAndUserId, arg.ID, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
